"""[DEPRECATED] Old Chapter 9 (multi-Agent) figure generator.

⚠️ DO NOT RUN: After the 2026-03-12 refactoring, chapter numbers changed (original Ch 9 → Ch 10).
The figures generated by this file actually correspond to the current [Chapter 10] content (multi-Agent collaboration), but are still saved as fig9-*.svg.
Running it would overwrite the current correct [Chapter 9] (multimodal & real-time interaction) figures, causing content misalignment.

The current correct Chapter 9 SVGs (multimodal/voice/Computer Use/VLA/Sim2Real) were
renamed from original fig8-*.svg in commit a33c88f on 2026-03-12; the current correct Chapter 10 SVGs
(multi-Agent collaboration) were **manually migrated** from the content originally generated by this file to fig10-*.svg.

To regenerate figures from this file, you should instead generate fig10-*.svg and reference them according to chapter10.md.

Original (now Ch 10) figure list:
  fig10-1:  Shared context vs independent context (concrete context windows)
  fig10-2:  Phase-based role switching (prompt/tool-set changes per phase)
  fig10-3:  Proposer-Reviewer loop (Slidev PPT iterative feedback)
  fig10-4:  Manager sequential coordination (sequential sub-agent delegation)
  fig10-5:  Book translation Agent architecture (NEW — Exp 10.4)
  fig10-6:  Manager parallel coordination (concurrent agents + message bus)
  fig10-7:  Phone + Computer dual Agent (NEW — Exp 10.5/10.6)
  fig10-8:  Parallel web scraping (NEW — Exp 10.7)
  fig10-9:  Handoff chain pattern (peer control passing)
  fig10-10: MetaGPT SOP pipeline (PM→Arch→Eng→QA with artifacts)
  fig10-11: AI town architecture (memory stream + reflection + planning)
  fig10-12: Voice Werewolf Agent system (NEW — Exp 10.9)
"""

import sys
print(
    "ERROR: gen_ch9_figs.py is DEPRECATED. Running it would overwrite the\n"
    "correct Chapter 9 (multimodal) figures with old Chapter 10 (multi-agent) content.\n"
    "See module docstring at the top of this file for the rename history.",
    file=sys.stderr,
)
sys.exit(2)
import sys, os

sys.path.insert(0, os.path.dirname(__file__))
from svg_lib import (
    SVG, COLORS, FONT, MONO,
    FS_TITLE, FS_BODY, FS_SMALL, FS_TINY, FS_LABEL, STROKE_W, CORNER_R,
    _escape,
)

OUT = os.path.join(os.path.dirname(__file__), 'images')


# ════════════════════════════════════════════════════════════════════
#  fig9-1: Shared context vs independent context
# ════════════════════════════════════════════════════════════════════

def fig9_1():
    W, H = 780, 560
    s = SVG(W, H)

    s.text(W // 2, 30, 'Konteks bersama vs konteks mandiri', size=FS_TITLE, bold=True)

    col_w = 350
    lx, rx = 20, W - col_w - 20

    # ── Left: shared context ──
    s.group_box(lx, 55, col_w, 480, 'Konteks bersama (Agen tunggal, beberapa fase)')

    ctx_x, ctx_w = lx + 15, col_w - 30
    phases = [
        ('Fase 1: Analis Persyaratan', 'medium', [
            'sys: "Tanggung jawab Anda adalah memahami persyaratan sepenuhnya..."',
            'tools: [ask_question, save_req]',
            'user: "Tulis skrip analisis CSV"',
            'agent: "Jenis file apa yang perlu diproses?"',
        ]),
        ('Fase 2: Rekayasa Perangkat Lunak', 'light', [
            'sys: "Tulis kode berdasarkan persyaratan yang telah dikonfirmasi..."',
            'tools: [write_file, execute_code]',
            'agent: write_file("analyze.py", ...)',
            'agent: execute_code("python test.py")',
        ]),
        ('Fase 3: Peninjau Kode', 'light', [
            'sys: "Tinjau kualitas dan keamanan kode..."',
            'tools: [run_linter, run_tests]',
            'agent: run_linter → 2 peringatan',
            'agent: approve_code()',
        ]),
    ]

    cy = 82
    for title, fill, lines in phases:
        ph = 18 + len(lines) * 18 + 10
        s.rect(ctx_x, cy, ctx_w, ph, fill=fill, rx=4)
        s.text(ctx_x + 8, cy + 14, title, size=FS_SMALL, bold=True, anchor='start')
        for i, ln in enumerate(lines):
            s.mono(ctx_x + 12, cy + 32 + i * 18, ln, size=12)
        cy += ph + 2

    s.rect(ctx_x, cy, ctx_w, 28, fill='code_bg', rx=3)
    s.text(ctx_x + ctx_w // 2, cy + 14, '↑ Semua fase berbagi riwayat percakapan yang sama', size=FS_TINY, bold=True)
    cy += 36

    s.text(lx + col_w // 2, cy + 10, '✓ Jejak eksekusi lengkap', size=FS_SMALL, fill='text_light')
    s.text(lx + col_w // 2, cy + 32, '✗ Konteks meluas dengan cepat', size=FS_SMALL, fill='text_light')

    # ── Right: independent context ──
    s.group_box(rx, 55, col_w, 480, 'Konteks mandiri (Multi-Agen sejati)')

    agents_data = [
        ('Agen Glosarium', [
            'sys: "Identifikasi istilah dan terjemahkan..."',
            'tools: [search_dict, write_file]',
            '→ glossary.json',
        ]),
        ('Agen Penerjemahan', [
            'sys: "Terjemahkan bab ini..."',
            'tools: [read_file, write_file]',
            '→ chapter3_id.md',
        ]),
        ('Agen Proofreading', [
            'sys: "Periksa konsistensi terminologi..."',
            'tools: [read_file, write_file]',
            '→ review_report.md',
        ]),
    ]

    ay = 82
    for name, lines in agents_data:
        ah = 18 + len(lines) * 18 + 8
        s.rect(rx + 15, ay, ctx_w, ah, fill='light', rx=4)
        s.text(rx + 23, ay + 14, name, size=FS_SMALL, bold=True, anchor='start')
        for i, ln in enumerate(lines):
            s.mono(rx + 27, ay + 32 + i * 18, ln, size=12)
        ay += ah + 8

    fs_y = ay + 5
    s.rect(rx + 15, fs_y, ctx_w, 65, fill='medium', rx=4)
    s.text(rx + 15 + ctx_w // 2, fs_y + 16, 'Sistem file bersama', size=FS_SMALL, bold=True)
    files = ['glossary.json', 'chapter3_id.md', 'review_report.md']
    s.mono(rx + 27, fs_y + 38, '  '.join(files), size=11)
    s.text(rx + 15 + ctx_w // 2, fs_y + 55, '+ Parameter pemanggilan alat meneruskan data terstruktur', size=FS_TINY, fill='text_light')

    s.text(rx + col_w // 2, fs_y + 82, '✓ Modular · Dapat Diperluas · Paralel', size=FS_SMALL, fill='text_light')
    s.text(rx + col_w // 2, fs_y + 104, '✗ Sinkronisasi informasi kompleks', size=FS_SMALL, fill='text_light')

    s.save(os.path.join(OUT, 'fig9-1.svg'))


# ════════════════════════════════════════════════════════════════════
#  fig9-2: Phase-based role switching
# ════════════════════════════════════════════════════════════════════

def fig9_2():
    W, H = 780, 520
    s = SVG(W, H)

    s.text(W // 2, 28, 'Pergantian peran berbasis fase: Tiga fase Agen Pemrograman', size=FS_TITLE, bold=True)

    phases = [
        ('Analis Persyaratan', 'medium',
         '"Tanggung jawab Anda adalah memahami persyaratan sepenuhnya.\nJangan terburu-buru mengimplementasikan; pada tahap ini\ntugas Anda adalah mengajukan pertanyaan dan mengonfirmasi."',
         ['ask_clarifying_question(q)', 'save_requirement(k, v)', 'complete_requirements_analysis()'],
         'complete_requirements_analysis()'),
        ('Rekayasa Perangkat Lunak', 'light',
         '"Tulis kode Python berkualitas tinggi berdasarkan persyaratan yang telah dikonfirmasi.\nIkuti praktik terbaik desain modular dan penanganan kesalahan."',
         ['write_file(path, content)', 'read_file(path)', 'execute_code(code)'],
         'submit_for_review()'),
        ('Peninjau Kode', '#e8e8e8',
         '"Evaluasi kualitas kode dari berbagai dimensi: \nkebenaran fungsional, standar pengkodean, \ndan keamanan. Terapkan pemikiran kritis."',
         ['run_linter(file)', 'run_tests(file)', 'analyze_complexity(file)'],
         None),
    ]

    s.rect(30, 55, W - 60, 28, fill='code_bg', rx=3)
    s.text(W // 2, 69, '▼ Alur berkelanjutan dalam konteks yang sama — riwayat percakapan dipertahankan sepenuhnya antar tahap ▼', size=FS_SMALL, bold=True)

    pw = 225
    gap = 18
    px_start = (W - 3 * pw - 2 * gap) // 2
    py = 100

    for i, (role, fill, prompt, tools, trigger) in enumerate(phases):
        x = px_start + i * (pw + gap)

        s.rect(x, py, pw, 380, fill=fill, rx=6)
        s.text(x + pw // 2, py + 22, f'Tahap {i + 1}', size=FS_TINY, fill='text_light')
        s.text(x + pw // 2, py + 42, role, size=FS_BODY, bold=True)

        s.rect(x + 8, py + 60, pw - 16, 88, fill='code_bg', rx=3)
        s.text(x + 14, py + 75, 'Prompt Sistem', size=FS_TINY, fill='text_light', anchor='start')
        for j, ln in enumerate(prompt.split('\n')):
            s.text(x + 14, py + 92 + j * 16, ln, size=12, anchor='start', fill='text_light')

        s.rect(x + 8, py + 158, pw - 16, 18 + len(tools) * 20, fill='white', rx=3)
        s.text(x + 14, py + 172, 'Set Alat', size=FS_TINY, fill='text_light', anchor='start')
        for j, tool in enumerate(tools):
            s.mono(x + 14, py + 190 + j * 20, tool, size=11)

        if trigger:
            ty = py + 290
            s.rect(x + 8, ty, pw - 16, 48, fill='dark', rx=12)
            s.text(x + pw // 2, ty + 16, 'Pemicu Transisi', size=FS_TINY, fill='white')
            s.mono(x + pw // 2, ty + 34, trigger, size=10, anchor='middle', fill='white')

        if i < 2:
            ax1 = x + pw + 2
            ax2 = x + pw + gap - 2
            ay = py + 310
            s.arrow(ax1, ay, ax2, ay)

    s.text(W // 2, H - 10, 'Transisi Peran: Perbarui prompt sistem + set alat, riwayat percakapan dan status terus dipertahankan',
           size=FS_SMALL, fill='text_light')

    s.save(os.path.join(OUT, 'fig9-2.svg'))


# ════════════════════════════════════════════════════════════════════
#  fig9-3: Proposer-Reviewer Loop (Slidev PPT Generation)
# ════════════════════════════════════════════════════════════════════

def fig9_3():
    W, H = 780, 520
    s = SVG(W, H)

    s.text(W // 2, 28, 'Putaran Pengusul-Peninjau: Pembuatan PPT Slidev', size=FS_TITLE, bold=True)

    # Editor (Proposer)
    ex, ey, ew, eh = 30, 65, 300, 200
    s.rect(ex, ey, ew, eh, fill='light')
    s.text(ex + ew // 2, ey + 22, 'Agen Pengusul', size=FS_BODY, bold=True)
    s.text(ex + 12, ey + 48, 'Input: Abstrak makalah yang diperluas (2000 karakter)', size=FS_TINY, anchor='start', fill='text_light')
    editor_lines = [
        '---',
        'theme: academic',
        '---',
        '# Mekanisme Perhatian Transformer',
        '',
        '## Ide Inti',
        '- Perhatian-diri menghitung Q·K^T/√d',
        '- Perhatian multi-kepala memproses secara paralel',
    ]
    ch = s.code_block(ex + 10, ey + 62, ew - 20, editor_lines, font_size=11, line_h=14)
    s.text(ex + ew // 2, ey + eh - 10, 'Memahami struktur konten → Mengurai menjadi slide', size=FS_TINY, fill='text_light')

    # Critic (Reviewer)
    cx, cy, cw, ch_h = 450, 65, 300, 200
    s.rect(cx, cy, cw, ch_h, fill='medium')
    s.text(cx + cw // 2, cy + 22, 'Agen Peninjau', size=FS_BODY, bold=True)

    s.rect(cx + 10, cy + 42, cw - 20, 38, fill='code_bg', rx=3)
    s.text(cx + 18, cy + 55, '① Rendering Slidev → PDF/PNG', size=FS_TINY, anchor='start')
    s.text(cx + 18, cy + 70, '② Evaluasi multi-dimensi Visi LLM', size=FS_TINY, anchor='start')

    feedback_items = [
        'Halaman  Jenis Masalah      Keparahan',
        'P3     Konten terlalu padat Tinggi',
        'P7     Font terlalu kecil   Sedang',
        'P11    Warna tidak cocok    Rendah',
    ]
    s.rect(cx + 10, cy + 86, cw - 20, 75, fill='code_bg', rx=3)
    s.text(cx + 18, cy + 100, 'Umpan Balik Terstruktur:', size=FS_TINY, anchor='start', bold=True)
    for i, fb in enumerate(feedback_items):
        s.mono(cx + 18, cy + 118 + i * 15, fb, size=11)
    s.text(cx + cw // 2, cy + ch_h - 10, 'Rendering + analisis visual → saran perbaikan yang dapat ditindaklanjuti', size=FS_TINY, fill='text_light')

    # Arrows between Editor and Critic
    mid_y1 = ey + 70
    mid_y2 = ey + eh - 50
    s.arrow(ex + ew + 2, mid_y1, cx - 2, mid_y1)
    s.text((ex + ew + cx) / 2, mid_y1 - 12, 'Kode Slidev', size=FS_SMALL, bold=True)

    s.arrow(cx - 2, mid_y2, ex + ew + 2, mid_y2)
    s.text((ex + ew + cx) / 2, mid_y2 + 16, 'Umpan Balik Terstruktur', size=FS_SMALL, bold=True)

    # Iteration timeline
    iy = 290
    s.rect(30, iy, W - 60, 100, fill='code_bg', rx=4)
    s.text(W // 2, iy + 18, 'Proses Perbaikan Iteratif', size=FS_BODY, bold=True)

    rounds = [
        ('Putaran 1', 'Draf 12 halaman\n5 masalah', 'light'),
        ('Putaran 2', '14 halaman (memisahkan halaman padat)\n2 masalah', 'light'),
        ('Putaran 3', '14 halaman (font dikoreksi)\n0 masalah ✓', 'medium'),
    ]
    rw = 190
    rx_start = (W - 3 * rw - 2 * 30) // 2
    for i, (name, desc, fill) in enumerate(rounds):
        rx = rx_start + i * (rw + 30)
        ry = iy + 35
        s.rect(rx, ry, rw, 52, fill=fill, rx=3)
        s.text(rx + 10, ry + 16, name, size=FS_SMALL, bold=True, anchor='start')
        for j, ln in enumerate(desc.split('\n')):
            s.text(rx + 10, ry + 34 + j * 16, ln, size=FS_TINY, anchor='start', fill='text_light')
        if i < 2:
            s.arrow(rx + rw + 4, ry + 26, rx + rw + 26, ry + 26, color='dark')

    # Why not single agent
    wy = 405
    s.rect(30, wy, W - 60, 90, fill='light', rx=4)
    s.text(W // 2, wy + 20, 'Mengapa tidak menggunakan agen tunggal?', size=FS_BODY, bold=True)

    single_x = 60
    dual_x = W // 2 + 20
    s.text(single_x, wy + 45, 'Agen Tunggal: Rendering × N putaran → ledakan konteks', size=FS_TINY, anchor='start', fill='text_light')
    s.text(single_x, wy + 63, '(Tangkapan layar 1080p = ribuan token × 14 halaman × 5 putaran)', size=FS_TINY, anchor='start', fill='text_light')
    s.text(dual_x, wy + 45, 'Agen Ganda: Peninjau hanya melihat versi saat ini', size=FS_TINY, anchor='start')
    s.text(dual_x, wy + 63, 'Editor hanya mengakumulasi umpan balik teks → konteks bersih', size=FS_TINY, anchor='start')

    s.save(os.path.join(OUT, 'fig9-3.svg'))


# ════════════════════════════════════════════════════════════════════
#  fig9-4: Manager sequential coordination
# ════════════════════════════════════════════════════════════════════

def fig9_4():
    W, H = 780, 480
    s = SVG(W, H)

    s.text(W // 2, 28, 'Koordinasi berurutan Manajer: Sub-Agen sebagai alat', size=FS_TITLE, bold=True)

    # Manager
    mx, my, mw, mh = 240, 60, 300, 100
    s.rect(mx, my, mw, mh, fill='medium')
    s.text(mx + mw // 2, my + 22, 'Agen Manajer', size=FS_BODY, bold=True)
    s.text(mx + mw // 2, my + 46, 'Pemahaman tugas → dekomposisi → penjadwalan → sintesis', size=FS_TINY, fill='text_light')
    s.text(mx + mw // 2, my + 66, 'Set alat: [call_agent_A, call_agent_B,', size=FS_TINY, fill='text_light')
    s.text(mx + mw // 2, my + 82, 'call_agent_C, search, write_file]', size=FS_TINY, fill='text_light')

    # Sub-agents in sequence
    agents = [
        ('Sub-Agen A', 'Pengumpulan data', 'Cari dokumentasi teknis\nEkstrak informasi kunci', 'light'),
        ('Sub-Agen B', 'Analisis dan pemrosesan', 'Bandingkan dan analisis data\nHasilkan laporan statistik', 'light'),
        ('Sub-Agen C', 'Pembuatan laporan', 'Tulis laporan akhir\nFormat output', 'light'),
    ]
    aw = 210
    ax_start = (W - 3 * aw - 2 * 25) // 2
    ay = 240

    for i, (name, role, desc, fill) in enumerate(agents):
        x = ax_start + i * (aw + 25)
        s.rect(x, ay, aw, 120, fill=fill, rx=6)
        s.text(x + aw // 2, ay + 20, name, size=FS_SMALL, bold=True)
        s.text(x + aw // 2, ay + 40, f'Peran: {role}', size=FS_TINY, fill='text_light')
        for j, ln in enumerate(desc.split('\n')):
            s.text(x + aw // 2, ay + 62 + j * 18, ln, size=FS_TINY, fill='text_light')

        badge_labels = [f'Langkah {i + 1}']
        s.badge(x + aw - 55, ay + 95, 50, 20, badge_labels[0], fill='dark', font_size=FS_TINY)

        # Arrow from Manager to sub-agent
        s.arrow(mx + mw // 2 - 100 + i * 100, my + mh + 2,
                x + aw // 2, ay - 2, color='dark')

        # Sequential arrow between sub-agents
        if i < 2:
            s.arrow(x + aw + 2, ay + 60, x + aw + 23, ay + 60)

    # Data flow
    dy = 380
    s.rect(30, dy, W - 60, 80, fill='code_bg', rx=4)
    s.text(W // 2, dy + 18, 'Alur eksekusi berurutan', size=FS_BODY, bold=True)

    flow_items = [
        'Manajer memanggil Agen A',
        '→ A mengembalikan data',
        '→ Manajer meneruskan ke B',
        '→ B mengembalikan analisis',
        '→ Manajer meneruskan ke C',
        '→ C mengembalikan laporan',
    ]
    fx_start = 35
    for i, item in enumerate(flow_items):
        s.text(fx_start + i * 123, dy + 42, item, size=FS_TINY, anchor='start',
               fill='text' if 'memanggil' in item or 'mengembalikan' in item else 'text_light')

    s.text(W // 2, dy + 65, 'Perspektif Manajer: memanggil Agen = memanggil alat (kirim permintaan → terima respons)',
           size=FS_SMALL, fill='text_light')

    s.save(os.path.join(OUT, 'fig9-4.svg'))


# ════════════════════════════════════════════════════════════════════
#  fig9-5: Book translation Agent architecture (Exp 9.4)
# ════════════════════════════════════════════════════════════════════

def fig9_5():
    W, H = 780, 540
    s = SVG(W, H)

    s.text(W // 2, 28, 'Eksperimen 9.4: Agen Penerjemah Buku — Mode Manajer', size=FS_TITLE, bold=True)

    # Manager at top
    mx, my, mw, mh = 240, 55, 300, 70
    s.rect(mx, my, mw, mh, fill='medium')
    s.text(mx + mw // 2, my + 22, 'Agen Manajer', size=FS_BODY, bold=True)
    s.text(mx + mw // 2, my + 48, 'Perencanaan tugas · Pemantauan kemajuan · Penanganan eksepsi · Sintesis hasil', size=FS_TINY, fill='text_light')

    # Three sub-agents
    sub_agents = [
        (30, 'Agen Glosarium', 'Glosarium istilah',
         ['Terima seluruh buku → Identifikasi istilah khusus', 'Cari kamus khusus + konvensi terjemahan', 'Output: glossary.json'],
         ['{"attention": "perhatian",', ' "transformer": "Transformer",', ' "backprop": "perambatan balik"}']),
        (270, 'Agen Penerjemah ×N', 'Terjemahan bab',
         ['Input: bab + glosarium + panduan', 'Terjemahkan istilah dengan ketat sesuai glosarium', 'Output: chapter{n}_id.md'],
         ['"...mekanisme perhatian menghitung kesamaan dari', ' Query·Key^T ..."']),
        (520, 'Agen Proofreading', 'Tinjauan teks lengkap',
         ['Pindai dan verifikasi konsistensi istilah', 'Periksa kelancaran dan keterbacaan', 'Output: review_report.md'],
         ['P3: Inkonsistensi "attention"→"fokus"', 'P8: Kalimat panjang disarankan untuk dipisah']),
    ]

    aw = 230
    ay = 170

    for x, name, role, desc, output in sub_agents:
        s.rect(x, ay, aw, 185, fill='light', rx=6)
        s.text(x + aw // 2, ay + 20, name, size=FS_SMALL, bold=True)
        s.text(x + aw // 2, ay + 38, role, size=FS_TINY, fill='text_light')

        for i, ln in enumerate(desc):
            s.text(x + 12, ay + 60 + i * 18, ln, size=FS_TINY, anchor='start', fill='text_light')

        s.rect(x + 8, ay + 115, aw - 16, 10 + len(output) * 15, fill='code_bg', rx=3)
        for i, ln in enumerate(output):
            s.mono(x + 14, ay + 128 + i * 15, ln, size=10)

        # Arrow from Manager
        s.arrow(mx + mw // 2, my + mh + 2, x + aw // 2, ay - 2, color='dark')

    # Sequential arrows between sub-agents
    s.arrow(30 + aw + 4, ay + 90, 270 - 4, ay + 90, label='Glosarium')
    s.arrow(270 + aw + 4, ay + 90, 520 - 4, ay + 90, label='Terjemahan')

    # Shared file system
    fy = 375
    s.rect(30, fy, W - 60, 70, fill='medium', rx=6)
    s.text(W // 2, fy + 18, 'Sistem file bersama', size=FS_BODY, bold=True)
    files = [
        ('glossary.json', 'Glosarium istilah'),
        ('chapter{1..10}_id.md', 'Terjemahan bab'),
        ('review_report.md', 'Laporan tinjauan'),
        ('translation_guide.md', 'Panduan terjemahan'),
    ]
    fw = (W - 80) // len(files)
    for i, (fname, desc) in enumerate(files):
        cx = 50 + i * fw + fw // 2
        s.mono(cx, fy + 40, fname, size=11, anchor='middle')
        s.text(cx, fy + 58, desc, size=FS_TINY, fill='text_light')

    # Key insight
    ky = 460
    s.rect(30, ky, W - 60, 60, fill='code_bg', rx=4)
    s.text(W // 2, ky + 18, 'Keuntungan isolasi konteks', size=FS_BODY, bold=True)
    s.text(W // 2, ky + 42,
           'Glosarium: hanya melihat istilah | Penerjemahan: hanya melihat bab saat ini + glosarium | Manajer: hanya mengelola indeks file',
           size=FS_TINY, fill='text_light')

    s.save(os.path.join(OUT, 'fig9-5.svg'))


# ════════════════════════════════════════════════════════════════════
#  fig9-6: Manager parallel coordination
# ════════════════════════════════════════════════════════════════════

def fig9_6():
    W, H = 780, 500
    s = SVG(W, H)

    s.text(W // 2, 28, 'Koordinasi paralel Manajer: arsitektur bus pesan', size=FS_TITLE, bold=True)

    # Orchestration Agent
    ox, oy, ow, oh = 240, 55, 300, 70
    s.rect(ox, oy, ow, oh, fill='medium')
    s.text(ox + ow // 2, oy + 22, 'Agen Orkestrasi', size=FS_BODY, bold=True)
    s.text(ox + ow // 2, oy + 48, 'Penjadwalan paralel · Pemantauan real-time · Agregasi hasil', size=FS_TINY, fill='text_light')

    # Message bus
    bus_y = 155
    s.rect(50, bus_y, W - 100, 36, fill='dark', rx=4)
    s.text(W // 2, bus_y + 18, 'Bus Pesan', size=FS_SMALL, fill='white', bold=True)

    s.arrow(ox + ow // 2, oy + oh + 2, ox + ow // 2, bus_y - 2)

    # Parallel agents
    agents = [
        ('Agen 1', 'Pengumpulan data', 'Berjalan ◎', 'light'),
        ('Agen 2', 'Analisis konten', 'Berjalan ◎', 'light'),
        ('Agen 3', 'Pembuatan Grafik', 'Selesai ✓', 'medium'),
        ('Agen 4', 'Validasi Format', 'Menunggu ○', 'code_bg'),
    ]
    aw = 160
    gap = 14
    total = len(agents) * aw + (len(agents) - 1) * gap
    ax_start = (W - total) // 2
    ay = 225

    for i, (name, role, status, fill) in enumerate(agents):
        x = ax_start + i * (aw + gap)
        s.rect(x, ay, aw, 100, fill=fill, rx=6)
        s.text(x + aw // 2, ay + 20, name, size=FS_SMALL, bold=True)
        s.text(x + aw // 2, ay + 40, role, size=FS_TINY, fill='text_light')
        s.text(x + aw // 2, ay + 65, status, size=FS_TINY,
               fill='text_light' if 'Menunggu' in status else 'text')
        s.text(x + aw // 2, ay + 82, 'Konteks Mandiri', size=FS_TINY, fill='text_light')

        s.arrow(x + aw // 2, bus_y + 38, x + aw // 2, ay - 2, color='dark')

    # Message examples
    my = 350
    s.rect(30, my, W - 60, 125, fill='code_bg', rx=4)
    s.text(W // 2, my + 18, 'Contoh Komunikasi Bus Pesan', size=FS_BODY, bold=True)

    messages = [
        ('Ork → Agen 1', '{"type":"start","task":"Kumpulkan makalah arxiv","params":{"query":"agen LLM"}}'),
        ('Agen 3 → Ork', '{"type":"completed","agent_id":"3","result":"charts/fig1.svg dihasilkan"}'),
        ('Agen 1 → Agen 2', '{"type":"data_ready","source":"agent_1","file":"raw_data.json"}'),
        ('Ork → Agen 4', '{"type":"start","depends_on":["agent_2","agent_3"]}'),
    ]
    for i, (sender, msg) in enumerate(messages):
        y = my + 40 + i * 22
        s.text(40, y, sender, size=FS_TINY, bold=True, anchor='start')
        s.mono(200, y, msg, size=10, anchor='start')

    s.save(os.path.join(OUT, 'fig9-6.svg'))


# ════════════════════════════════════════════════════════════════════
#  fig9-7: Phone + Computer Dual Agent (Exp 9.5/9.6)
# ════════════════════════════════════════════════════════════════════

def fig9_7():
    W, H = 780, 560
    s = SVG(W, H)

    s.text(W // 2, 28, 'Eksperimen 9.5/9.6: Agen Ganda Telepon + Komputer', size=FS_TITLE, bold=True)

    # Phone Agent (left)
    px, py, pw, ph = 30, 65, 310, 240
    s.rect(px, py, pw, ph, fill='light', rx=6)
    s.text(px + pw // 2, py + 22, 'Agen Telepon', size=FS_BODY, bold=True)
    s.text(px + pw // 2, py + 42, 'Node.js · Panggilan Suara Real-time', size=FS_TINY, fill='text_light')

    phone_pipeline = [
        ('Suara Pengguna', 'Input Mikrofon', 'medium'),
        ('VAD + ASR', 'Silero VAD → Transkripsi STT', 'light'),
        ('Inferensi LLM', 'Pahami Niat + Ekstrak Informasi', 'light'),
        ('Sintesis TTS', 'Hasilkan Balasan Suara → Pemutaran', 'medium'),
    ]
    for i, (label, desc, fill) in enumerate(phone_pipeline):
        y = py + 60 + i * 42
        s.rect(px + 10, y, pw - 20, 36, fill=fill, rx=3)
        s.text(px + 20, y + 14, label, size=FS_TINY, bold=True, anchor='start')
        s.text(px + 20, y + 28, desc, size=11, anchor='start', fill='text_light')
        if i < len(phone_pipeline) - 1:
            s.arrow(px + pw // 2, y + 38, px + pw // 2, y + 42, color='dark')

    # Computer Agent (right)
    cx, cy, cw, ch_h = 440, 65, 310, 240
    s.rect(cx, cy, cw, ch_h, fill='light', rx=6)
    s.text(cx + cw // 2, cy + 22, 'Agen Komputer', size=FS_BODY, bold=True)
    s.text(cx + cw // 2, cy + 42, 'Python · Otomatisasi Browser', size=FS_TINY, fill='text_light')

    comp_pipeline = [
        ('Tangkapan Layar', 'Halaman Browser Saat Ini', 'medium'),
        ('Visi LLM', 'Pahami Struktur Halaman + Bidang Formulir', 'light'),
        ('Perencanaan Tindakan', 'Temukan Bidang → Rencanakan Urutan Input', 'light'),
        ('Eksekusi Tindakan', 'Klik / Input / Kirim', 'medium'),
    ]
    for i, (label, desc, fill) in enumerate(comp_pipeline):
        y = cy + 60 + i * 42
        s.rect(cx + 10, y, cw - 20, 36, fill=fill, rx=3)
        s.text(cx + 20, y + 14, label, size=FS_TINY, bold=True, anchor='start')
        s.text(cx + 20, y + 28, desc, size=11, anchor='start', fill='text_light')
        if i < len(comp_pipeline) - 1:
            s.arrow(cx + cw // 2, y + 38, cx + cw // 2, y + 42, color='dark')

    # WebSocket connection between agents
    ws_y = py + ph + 15
    s.rect(30, ws_y, W - 60, 36, fill='dark', rx=4)
    s.text(W // 2, ws_y + 18, 'Komunikasi Dua Arah WebSocket (ws://localhost:8849)', size=FS_SMALL, fill='white', bold=True)

    s.arrow(px + pw // 2, py + ph + 2, px + pw // 2, ws_y - 2, color='dark')
    s.arrow(cx + cw // 2, cy + ch_h + 2, cx + cw // 2, ws_y - 2, color='dark')

    # Message examples
    my = ws_y + 50
    s.rect(30, my, W - 60, 150, fill='code_bg', rx=4)
    s.text(W // 2, my + 18, 'Aliran Pesan Dua Arah Real-time (Gunakan telepon dan komputer bersamaan)', size=FS_BODY, bold=True)

    msgs = [
        ('Telepon → Komputer', '[FROM_PHONE_AGENT] Pengguna mengatakan namanya adalah Budi', '→'),
        ('Komputer → Telepon', '[FROM_COMPUTER_AGENT] Nama terisi, nomor KTP diperlukan', '←'),
        ('Telepon → Komputer', '[FROM_PHONE_AGENT] Nomor KTP 310101199001011234', '→'),
        ('Komputer → Telepon', '[FROM_COMPUTER_AGENT] Formulir dikirim, pendaftaran berhasil', '←'),
    ]
    for i, (sender, content, direction) in enumerate(msgs):
        y = my + 42 + i * 26
        s.text(42, y, sender, size=FS_TINY, bold=True, anchor='start',
               fill='text' if '→' == direction else 'text_light')
        s.mono(210, y, content, size=10, anchor='start')

    # Key point
    s.text(W // 2, my + 140,
           'Kunci: Dua agen menjalankan loop ReAct independen secara paralel tanpa memblokir satu sama lain',
           size=FS_SMALL, fill='text_light')

    s.save(os.path.join(OUT, 'fig9-7.svg'))


# ════════════════════════════════════════════════════════════════════
#  fig9-8: Parallel Web Scraping Agent (Exp 9.7)
# ════════════════════════════════════════════════════════════════════

def fig9_8():
    W, H = 780, 530
    s = SVG(W, H)

    s.text(W // 2, 28, 'Eksperimen 9.7: Web Scraping Paralel — Penghentian Berjenjang', size=FS_TITLE, bold=True)

    # Orchestration Agent
    ox, oy, ow, oh = 230, 55, 320, 65
    s.rect(ox, oy, ow, oh, fill='medium')
    s.text(ox + ow // 2, oy + 20, 'Agen Orkestrasi', size=FS_BODY, bold=True)
    s.text(ox + ow // 2, oy + 44, 'Pembuatan dinamis · Pemantauan real-time · Penghentian berjenjang', size=FS_TINY, fill='text_light')

    # Parallel Computer Use Agents
    agents = [
        ('Agen 1', 'cs.edu.cn', 'Mencari... ◎', 'light'),
        ('Agen 2', 'math.edu.cn', 'Tidak ditemukan ✗', '#e8e8e8'),
        ('Agen 3', 'phys.edu.cn', 'Ditemukan! ✓', 'medium'),
        ('Agen 4', 'chem.edu.cn', 'Dihentikan ⊘', 'code_bg'),
        ('Agen 5', 'bio.edu.cn', 'Dihentikan ⊘', 'code_bg'),
    ]
    aw = 130
    gap = 12
    total_w = len(agents) * aw + (len(agents) - 1) * gap
    ax_start = (W - total_w) // 2
    ay = 160

    for i, (name, url, status, fill) in enumerate(agents):
        x = ax_start + i * (aw + gap)
        s.rect(x, ay, aw, 95, fill=fill, rx=4)
        s.text(x + aw // 2, ay + 16, name, size=FS_SMALL, bold=True)
        s.mono(x + aw // 2, ay + 35, url, size=10, anchor='middle')
        s.text(x + aw // 2, ay + 55, 'Pencarian Direktori Fakultas', size=FS_TINY, fill='text_light')
        s.text(x + aw // 2, ay + 75, status, size=FS_TINY,
               bold=('Ditemukan' in status), fill='text' if 'Ditemukan' in status else 'text_light')

        s.arrow(ox + ow // 2, oy + oh + 2, x + aw // 2, ay - 2, color='dark')

    # Cascade termination flow
    ty = 280
    s.rect(30, ty, W - 60, 120, fill='code_bg', rx=4)
    s.text(W // 2, ty + 18, 'Garis Waktu Penghentian Berjenjang', size=FS_BODY, bold=True)

    timeline = [
        ('t=0d', 'Mulai 5 agen\npencarian paralel untuk guru "Zhang Wei"'),
        ('t=12d', 'Agen 2 selesai\nTidak ditemukan → Keluar normal'),
        ('t=18d', 'Agen 3 menemukan target!\nKirim target_found'),
        ('t=18.1d', 'Ork menyiarkan hentikan\nke Agen 1,4,5'),
        ('t=19d', 'Semua mengonfirmasi penghentian\nAgregasi hasil dan kembalikan'),
    ]
    tw = 130
    tx_start = (W - len(timeline) * tw) // 2
    for i, (time, desc) in enumerate(timeline):
        x = tx_start + i * tw
        s.text(x + tw // 2, ty + 42, time, size=FS_SMALL, bold=True)
        for j, ln in enumerate(desc.split('\n')):
            s.text(x + tw // 2, ty + 60 + j * 16, ln, size=FS_TINY, fill='text_light')
        if i < len(timeline) - 1:
            s.arrow(x + tw - 2, ty + 55, x + tw + 4, ty + 55, color='dark')

    # Result and comparison
    ry = 420
    s.rect(30, ry, 340, 85, fill='light', rx=4)
    s.text(200, ry + 18, 'Hasil ditemukan', size=FS_BODY, bold=True)
    result_lines = [
        'Nama: Zhang Wei   Sekolah: Fakultas Fisika',
        'Jabatan: Profesor   Bidang: Komputasi Kuantum',
        'Email: zhangwei@phys.edu.cn',
    ]
    for i, ln in enumerate(result_lines):
        s.mono(50, ry + 40 + i * 16, ln, size=11)

    s.rect(400, ry, 350, 85, fill='medium', rx=4)
    s.text(575, ry + 18, 'Perbandingan Kinerja', size=FS_BODY, bold=True)
    s.text(420, ry + 42, 'Serial: 10 situs web × 30d = ~5 menit', size=FS_TINY, anchor='start', fill='text_light')
    s.text(420, ry + 60, 'Paralel: 18d untuk menemukan + 1d untuk menghentikan = 19d', size=FS_TINY, anchor='start', bold=True)
    s.text(420, ry + 78, 'Peningkatan: ~15× (dengan optimasi penghentian berjenjang)', size=FS_TINY, anchor='start', fill='text_light')

    s.save(os.path.join(OUT, 'fig9-8.svg'))


# ════════════════════════════════════════════════════════════════════
#  fig9-9: Handoff Chain Pattern
# ════════════════════════════════════════════════════════════════════

def fig9_9():
    W, H = 780, 440
    s = SVG(W, H)

    s.text(W // 2, 28, 'Pola Rantai Serah Terima: Serah terima peer-to-peer + Kolaborasi berbasis kontrak', size=FS_TITLE, bold=True)

    nodes = [
        ('Agen A', 'Analisis Persyaratan', 'Output: dokumen persyaratan terstruktur \nspec.json', 'medium'),
        ('Agen B', 'Desain Arsitektur', 'Output: dokumen desain teknis \ndesign.md', 'light'),
        ('Agen C', 'Implementasi Kode', 'Output: kode sumber \nsrc/*.py', 'light'),
        ('Agen D', 'Verifikasi Pengujian', 'Output: laporan pengujian \ntest_report.md', 'medium'),
    ]

    nw, nh = 160, 130
    gap = 22
    total_w = len(nodes) * nw + (len(nodes) - 1) * gap
    nx_start = (W - total_w) // 2
    ny = 60

    for i, (name, role, output, fill) in enumerate(nodes):
        x = nx_start + i * (nw + gap)
        s.rect(x, ny, nw, nh, fill=fill, rx=6)
        s.text(x + nw // 2, ny + 20, name, size=FS_SMALL, bold=True)
        s.text(x + nw // 2, ny + 40, role, size=FS_TINY, fill='text_light')

        s.rect(x + 8, ny + 55, nw - 16, 50, fill='code_bg', rx=3)
        for j, ln in enumerate(output.split('\n')):
            s.text(x + nw // 2, ny + 72 + j * 16, ln, size=FS_TINY, fill='text_light')

        s.text(x + nw // 2, ny + nh - 8, 'Serah terima setelah selesai →', size=FS_TINY, fill='text_light')

        if i < len(nodes) - 1:
            s.arrow(x + nw + 4, ny + nh // 2, x + nw + gap - 4, ny + nh // 2)

    # Handoff data detail
    hy = 215
    s.rect(30, hy, W - 60, 90, fill='code_bg', rx=4)
    s.text(W // 2, hy + 18, 'Konten Serah Terima (Contoh Agen A → Agen B)', size=FS_BODY, bold=True)

    handoff_fields = [
        ('Kondisi Pemicu', 'A menyelesaikan dokumen persyaratan → is_complete=True'),
        ('Agen Target', 'target="architect" (Agen B)'),
        ('Konten Serah Terima', 'files=["spec.json"] + summary="Sistem e-commerce: 3 layanan mikro, REST API"'),
        ('Status Pasca-serah terima', 'status="exit" (bebaskan sumber daya, tidak tetap siaga)'),
    ]
    for i, (field, value) in enumerate(handoff_fields):
        y = hy + 38 + i * 16
        s.text(42, y, field + ':', size=FS_TINY, bold=True, anchor='start')
        s.text(200, y, value, size=FS_TINY, anchor='start', fill='text_light')

    # Comparison with Manager mode
    cy = 320
    s.rect(30, cy, 340, 100, fill='light', rx=4)
    s.text(200, cy + 18, 'Keuntungan Desentralisasi', size=FS_SMALL, bold=True)
    advantages = [
        '✓ Tidak perlu Manajer pusat untuk memahami semua peran',
        '✓ Batas tanggung jawab yang jelas, decoupling antarmuka',
        '✓ Insinyur dapat memiliki beberapa instans paralel',
    ]
    for i, adv in enumerate(advantages):
        s.text(48, cy + 42 + i * 20, adv, size=FS_TINY, anchor='start', fill='text_light')

    s.rect(400, cy, 350, 100, fill='light', rx=4)
    s.text(575, cy + 18, 'Keterbatasan Desentralisasi', size=FS_SMALL, bold=True)
    limits = [
        '✗ Kurangnya perspektif optimasi global',
        '✗ Penanganan eksepsi yang sulit (tanpa koordinasi pusat)',
        '✗ Proses tetap, sulit untuk disesuaikan secara dinamis',
    ]
    for i, lim in enumerate(limits):
        s.text(418, cy + 42 + i * 20, lim, size=FS_TINY, anchor='start', fill='text_light')

    s.save(os.path.join(OUT, 'fig9-9.svg'))


# ════════════════════════════════════════════════════════════════════
#  fig9-10: MetaGPT SOP Pipeline
# ════════════════════════════════════════════════════════════════════

def fig9_10():
    W, H = 780, 530
    s = SVG(W, H)

    s.text(W // 2, 28, 'Pipeline SOP MetaGPT: Berbasis Dokumen Terstandarisasi', size=FS_TITLE, bold=True)

    roles = [
        ('Manajer Produk', 'medium',
         'Input: Deskripsi Persyaratan Pengguna',
         ['Daftar Fitur + Prioritas', 'Kisah Pengguna (5 item)', 'Kriteria Penerimaan'],
         'docs/PRD.md'),
        ('Arsitek', 'light',
         'Input: PRD.md',
         ['Tumpukan Teknologi: FastAPI+React', 'Spesifikasi API (OpenAPI)', 'Skema Database'],
         'docs/design.md'),
        ('Insinyur ×3', 'light',
         'Input: design.md + spesifikasi modul',
         ['Modul A: Layanan Pengguna', 'Modul B: Layanan Pesanan', 'Modul C: Layanan Pembayaran'],
         'src/*.py'),
        ('Insinyur QA', 'medium',
         'Input: src/ + PRD.md',
         ['Pengujian Unit (pytest)', 'Pengujian Integrasi (API)', 'Laporan Bug → Insinyur'],
         'docs/test_report.md'),
    ]

    rw = 170
    gap = 16
    total_w = len(roles) * rw + (len(roles) - 1) * gap
    rx_start = (W - total_w) // 2
    ry = 55

    for i, (name, fill, input_desc, outputs, artifact) in enumerate(roles):
        x = rx_start + i * (rw + gap)

        s.rect(x, ry, rw, 230, fill=fill, rx=6)
        s.text(x + rw // 2, ry + 20, name, size=FS_SMALL, bold=True)

        s.text(x + 8, ry + 42, input_desc, size=11, anchor='start', fill='text_light')

        s.rect(x + 8, ry + 58, rw - 16, 20 + len(outputs) * 16, fill='code_bg', rx=3)
        s.text(x + 14, ry + 72, 'Output:', size=FS_TINY, bold=True, anchor='start')
        for j, out in enumerate(outputs):
            s.text(x + 14, ry + 88 + j * 16, out, size=11, anchor='start', fill='text_light')

        s.rect(x + 8, ry + 168, rw - 16, 30, fill='dark', rx=12)
        s.mono(x + rw // 2, ry + 183, artifact, size=11, anchor='middle', fill='white')

        if i < len(roles) - 1:
            ax1 = x + rw + 2
            ax2 = x + rw + gap - 2
            s.arrow(ax1, ry + 115, ax2, ry + 115)

    # QA → Engineer feedback loop
    qa_x = rx_start + 3 * (rw + gap) + rw // 2
    eng_x = rx_start + 2 * (rw + gap) + rw // 2
    s.arrow_curved(qa_x, ry + 230 + 5, eng_x, ry + 230 + 5, curve=-30, label='Perbaikan Bug', dash=True)

    # Shared file system
    fy = 310
    s.rect(30, fy, W - 60, 50, fill='medium', rx=4)
    s.text(W // 2, fy + 16, 'Direktori Proyek Bersama', size=FS_SMALL, bold=True)
    s.mono(W // 2, fy + 36, 'docs/PRD.md  docs/design.md  src/*.py  docs/test_report.md',
           size=11, anchor='middle')

    # Key insight
    ky = 375
    s.rect(30, ky, W - 60, 130, fill='code_bg', rx=4)
    s.text(W // 2, ky + 18, 'Desain Inti MetaGPT', size=FS_BODY, bold=True)

    insights = [
        ('Dokumen Terstandarisasi', 'Setiap peran menghasilkan format yang jelas — hilir hanya perlu memahami format, bukan proses pemikiran hulu'),
        ('Decoupling Antarmuka', 'Tingkatkan PM (beralih ke model yang lebih kuat) — selama output sesuai dengan format PRD, hilir tidak memerlukan modifikasi'),
        ('Tanpa Manajer', 'Kontrol mengalir secara alami di sepanjang DAG: PM→Arch→Eng→QA, tanpa overhead penjadwalan pusat'),
        ('Saluran Eksepsi', 'Kegagalan uji QA → Laporan bug dirutekan oleh modul kembali ke Insinyur → perbaikan iteratif'),
    ]
    for i, (title, desc) in enumerate(insights):
        y = ky + 42 + i * 24
        s.text(42, y, '▸ ' + title, size=FS_SMALL, bold=True, anchor='start')
        s.text(200, y, desc, size=FS_TINY, anchor='start', fill='text_light')

    s.save(os.path.join(OUT, 'fig9-10.svg'))


# ════════════════════════════════════════════════════════════════════
#  Fig9-11: VLA Architecture (Vision-Language-Action) — Comparison of Three Technical Paths
# ════════════════════════════════════════════════════════════════════

def fig9_11():
    W, H = 900, 620
    s = SVG(W, H)

    #  Common Input
    in_x, in_y, in_w, in_h = 230, 55, 440, 64
    s.rect(in_x, in_y, in_w, in_h, fill='medium', rx=6)
    s.text(in_x + in_w / 2, in_y + 22, 'Input Umum: gambar kamera + instruksi bahasa', size=FS_SMALL, bold=True)
    s.text(in_x + in_w / 2, in_y + 44, '"Masukkan balok merah ke dalam kotak biru"', size=FS_TINY, fill='text_light')

    #  Arrows leading to three branches
    s.arrow(in_x + 70, in_y + in_h + 2, 145, 165)   # → OpenVLA
    s.arrow(W / 2, in_y + in_h + 2, W / 2, 165)     # → π₀
    s.arrow(in_x + in_w - 70, in_y + in_h + 2, 755, 165)  # → RT-2

    #  Three-Column Architecture
    col_w, col_gap = 270, 30
    cols_total = 3 * col_w + 2 * col_gap
    sx0 = (W - cols_total) / 2  # = 30

    columns = [
        ('OpenVLA', 'Sumber terbuka · token tindakan diskrit', 'light', [
            ('Enkoder Visi', 'DINOv2 + SigLIP', 'Ekstrak fitur piksel'),
            ('Tulang punggung LLM', 'Llama 2 (7B)', 'Pahami instruksi dan adegan'),
            ('Metode decoding', 'Autoregresif · token teks', 'Diskritisasi tindakan menjadi opsi'),
            ('Output tindakan', 'Token "a=[3,−2,5,...]"', 'Hasilkan nilai kontrol 7-DOF langkah demi langkah'),
        ]),
        ('π₀（Pi-Zero）', 'Kebijakan difusi · lintasan halus', 'medium', [
            ('Enkoder Visi', 'Fusi multi-tampilan ViT', 'Ekstrak fitur piksel'),
            ('Campuran-Transformer', 'Tulang punggung terpisah cepat-lambat', 'Pemikiran lambat bahasa + pemikiran cepat kontrol'),
            ('Metode decoding', 'Iterasi denoising difusi', 'Perbaikan lintasan dari kasar ke halus'),
            ('Output tindakan', 'Urutan tindakan kontinu (50 langkah/batch)', 'Sinyal kontrol halus frekuensi tinggi'),
        ]),
        ('RT-2', 'Model bahasa sebagai model tindakan', 'light', [
            ('Tulang punggung Visi-bahasa', 'PaLI-X / PaLM-E', 'Pemahaman end-to-end VLM'),
            ('Representasi tindakan', 'Tindakan → token bahasa alami', '"gerakkan lengan 5cm ke kanan"'),
            ('Metode decoding', 'Gunakan kembali autoregresi VLM', 'Bobot bersama dengan generasi teks'),
            ('Output tindakan', 'Deskripsi teks → penguraian pengontrol', 'Mewarisi generalisasi semantik VLM'),
        ]),
    ]

    top_y = 165
    title_h = 50
    row_h = 80
    for i, (name, tag, fill, rows) in enumerate(columns):
        cx = sx0 + i * (col_w + col_gap)
        #Column container
        col_total_h = title_h + len(rows) * row_h + 14
        s.rect(cx, top_y, col_w, col_total_h, fill='white', stroke='border')
        #Title bar
        s.rect(cx, top_y, col_w, title_h, fill=fill)
        s.text(cx + col_w / 2, top_y + 18, name, size=FS_BODY, bold=True)
        s.text(cx + col_w / 2, top_y + 38, tag, size=FS_TINY, fill='text_light')

        #Rows
        for j, (label, value, hint) in enumerate(rows):
            ry = top_y + title_h + 8 + j * row_h
            s.rect(cx + 10, ry, col_w - 20, row_h - 8, fill='code_bg', rx=4)
            s.text(cx + col_w / 2, ry + 18, label, size=FS_TINY, bold=True)
            s.text(cx + col_w / 2, ry + 38, value, size=FS_TINY)
            s.text(cx + col_w / 2, ry + 56, hint, size=FS_TINY, fill='text_light')

    #  Bottom: unified output layer
    out_y = top_y + title_h + 4 * row_h + 14 + 24
    s.rect(30, out_y, W - 60, 50, fill='darker', rx=6)
    s.text(W / 2, out_y + 18,
           'Sinyal kontrol robot: Sudut sambungan 7-DOF / pose end-effector',
           size=FS_SMALL, bold=True, fill='white')
    s.text(W / 2, out_y + 36,
           'Perbedaannya terletak pada "bagaimana memberi tahu robot apa yang harus dilakukan selanjutnya," tetapi pada akhirnya bermuara pada antarmuka kontrol terpadu',
           size=FS_TINY, fill='white')

    s.save(os.path.join(OUT, 'fig9-11.svg'))


# ════════════════════════════════════════════════════════════════════
#  Fig 9-12: Voice Werewolf Agent System (Exp 9.9)
# ════════════════════════════════════════════════════════════════════

def fig9_12():
    W, H = 780, 550
    s = SVG(W, H)

    s.text(W // 2, 28, 'Eksperimen 9.9: Werewolf Suara — Kontrol Izin Informasi', size=FS_TITLE, bold=True)

    # Judge (code-driven)
    jx, jy, jw, jh = 260, 55, 260, 75
    s.rect(jx, jy, jw, jh, fill='dark', rx=6)
    s.text(jx + jw // 2, jy + 20, 'Hakim (berbasis kode)', size=FS_BODY, bold=True, fill='white')
    s.text(jx + jw // 2, jy + 42, 'Status permainan · Kontrol fase · Distribusi informasi', size=FS_TINY, fill='white')
    s.text(jx + jw // 2, jy + 58, 'Malam → Siang → Pemungutan Suara → Penyelesaian', size=FS_TINY, fill='white')

    # Role agents
    roles = [
        (40, 'Werewolf 1', '🐺', 'medium',
         ['Terlihat: Identitas rekan', 'Strategi: Menyamar sebagai warga', 'Malam: Pilih target']),
        (185, 'Werewolf 2', '🐺', 'medium',
         ['Terlihat: Identitas rekan', 'Strategi: Ikuti suara warga', 'Malam: Negosiasi target']),
        (330, 'Penerawang', '🔮', 'light',
         ['Terlihat: Hasil investigasi', 'Strategi: Pilih waktu untuk ungkap', 'Malam: Periksa 1 orang']),
        (475, 'Penyihir', '🧪', 'light',
         ['Terlihat: Kematian/penyembuhan', 'Strategi: Simpan ramuan/racun', 'Malam: Selamatkan/racun 1 orang']),
        (620, 'Warga ×2', '👤', '#e8e8e8',
         ['Terlihat: Hanya info publik', 'Strategi: Penalaran logis', 'Siang: Analisis ucapan']),
    ]

    aw, ay = 135, 180
    for x, name, icon, fill, info in roles:
        s.rect(x, ay, aw, 140, fill=fill, rx=6)
        s.text(x + aw // 2, ay + 18, f'{icon} {name}', size=FS_SMALL, bold=True)
        for i, ln in enumerate(info):
            s.text(x + aw // 2, ay + 42 + i * 20, ln, size=11, fill='text_light')

        # Arrow from Judge
        s.arrow(jx + jw // 2, jy + jh + 2, x + aw // 2, ay - 2, color='dark')

        # Permission badge
        if 'Werewolf' in name:
            s.badge(x + aw - 45, ay + aw - 15, 40, 18, 'Pengetahuan bersama', fill='darker', font_size=11)
        elif 'Penerawang' in name:
            s.badge(x + aw - 55, ay + aw - 15, 50, 18, 'Hasil investigasi', fill='darker', font_size=10)

    # Info permission control
    iy = 340
    s.rect(30, iy, W - 60, 90, fill='code_bg', rx=4)
    s.text(W // 2, iy + 18, 'Kontrol izin informasi: hakim memfilter konteks berdasarkan peran', size=FS_BODY, bold=True)

    perms = [
        ('Werewolf', 'Semua identitas werewolf + diskusi malam + ucapan publik'),
        ('Penerawang', 'Hasil investigasi (hanya milik sendiri) + ucapan publik'),
        ('Penyihir', 'Kematian di malam hari + status penawar/racun + ucapan publik'),
        ('Warga', 'Hanya ucapan publik + catatan pemungutan suara (tanpa informasi pribadi)'),
    ]
    pw = (W - 80) // 2
    for i, (role, perm) in enumerate(perms):
        row, col = i // 2, i % 2
        x = 50 + col * pw
        y = iy + 40 + row * 22
        s.text(x, y, role + ':', size=FS_TINY, bold=True, anchor='start')
        s.text(x + 75, y, perm, size=FS_TINY, anchor='start', fill='text_light')

    # Voice interaction
    vy = 445
    s.rect(30, vy, W - 60, 85, fill='light', rx=4)
    s.text(W // 2, vy + 18, 'Interaksi suara real-time (ASR + LLM + TTS)', size=FS_BODY, bold=True)

    voice_flow = [
        ('Diskusi siang', 'Hakim mengatur urutan bicara\nberbicara berdasarkan urutan kursi'),
        ('Fase voting', 'Kumpulkan semua suara pemain\nhitung suara dan umumkan hasil'),
        ('Fase malam', 'Hakim membangunkan peran secara berurutan\nsaluran suara pribadi'),
        ('Pemain manusia', 'Penetapan peran acak\nvoting/bicara berbasis suara'),
    ]
    vw = (W - 80) // len(voice_flow)
    for i, (title, desc) in enumerate(voice_flow):
        cx = 50 + i * vw + vw // 2
        s.text(cx, vy + 42, title, size=FS_SMALL, bold=True)
        for j, ln in enumerate(desc.split('\n')):
            s.text(cx, vy + 60 + j * 16, ln, size=FS_TINY, fill='text_light')

    s.save(os.path.join(OUT, 'fig9-12.svg'))


# ════════════════════════════════════════════════════════════════════
#  Main
# ════════════════════════════════════════════════════════════════════

def main():
    os.makedirs(OUT, exist_ok=True)

    figs = [
        ('fig9-1', fig9_1),
        ('fig9-2', fig9_2),
        ('fig9-3', fig9_3),
        ('fig9-4', fig9_4),
        ('fig9-5', fig9_5),
        ('fig9-6', fig9_6),
        ('fig9-7', fig9_7),
        ('fig9-8', fig9_8),
        ('fig9-9', fig9_9),
        ('fig9-10', fig9_10),
        ('fig9-11', fig9_11),
        ('fig9-12', fig9_12),
    ]

    for name, func in figs:
        func()
        print(f'  ✓ {name}')

    print(f'\\nGenerated {len(figs)} figures in {OUT}/')


if __name__ == '__main__':
    main()
